# Generated by Django 5.0.4 on 2024-04-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_menu', models.ImageField(default='img_menu/menu.svg', upload_to='img_menu')),
                ('name', models.CharField(max_length=20, verbose_name='Назва')),
                ('link', models.CharField(max_length=20, verbose_name='Посилання')),
                ('language', models.TextField(max_length=2, verbose_name='Мова')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункти меню',
            },
        ),
    ]
