# Generated by Django 5.0.4 on 2024-04-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='img_menu',
            field=models.FileField(default='img_menu/menu.svg', upload_to='img_menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='language',
            field=models.CharField(max_length=5, verbose_name='Мова'),
        ),
    ]
