# Generated by Django 5.0.4 on 2024-04-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natos', '0002_alter_menu_img_menu_alter_menu_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(default='pictures/test.svg', upload_to='pictures')),
                ('name', models.CharField(max_length=20, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Зображення',
                'verbose_name_plural': 'Зображення',
            },
        ),
        migrations.CreateModel(
            name='Sounds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sound', models.FileField(default='sounds/test.midi', upload_to='sounds')),
                ('name', models.CharField(max_length=20, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Звуки',
                'verbose_name_plural': 'Звуки',
            },
        ),
    ]
