# Generated by Django 5.0.4 on 2024-04-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natos', '0003_pictures_sounds'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_game', models.FileField(default='img_game/game.svg', upload_to='img_game')),
                ('name', models.CharField(max_length=20, verbose_name='Назва')),
                ('link', models.CharField(max_length=20, verbose_name='Посилання')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Гра',
                'verbose_name_plural': 'Ігри',
            },
        ),
    ]
