# Generated by Django 5.0.4 on 2024-04-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natos', '0004_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nat_web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=100, verbose_name='Опис')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'новина',
                'verbose_name_plural': 'новини',
            },
        ),
    ]
