# Generated by Django 5.0.4 on 2024-04-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natos', '0005_nat_web'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nat_web_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(default='pictures/test.svg', upload_to='pictures')),
                ('name', models.CharField(max_length=30, verbose_name='Назва')),
                ('description', models.CharField(max_length=100, verbose_name='Опис')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'зображення',
                'verbose_name_plural': 'зображення',
            },
        ),
    ]
