# Generated by Django 5.0.4 on 2024-05-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natos', '0006_nat_web_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_game', models.FileField(default='img_web/site.svg', upload_to='img_web')),
                ('name', models.CharField(max_length=20, verbose_name='Назва')),
                ('link', models.CharField(max_length=20, verbose_name='Посилання')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Сайт',
                'verbose_name_plural': 'Сайти',
            },
        ),
        migrations.AlterModelOptions(
            name='nat_web',
            options={'verbose_name': 'Новина сайт', 'verbose_name_plural': 'Новина сайт'},
        ),
        migrations.AlterModelOptions(
            name='nat_web_img',
            options={'verbose_name': 'Зображення сайт', 'verbose_name_plural': 'Зображення сайт'},
        ),
    ]
