# Generated by Django 5.0.4 on 2024-05-22 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natos', '0007_website_alter_nat_web_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(default='img_ava/avatar.svg', upload_to='img_ava')),
                ('key', models.TextField(max_length=10, verbose_name='Ключ')),
                ('dict_img', models.TextField(blank=True, verbose_name='Словник з зображенями')),
                ('dict_sound', models.TextField(blank=True, verbose_name='Словник з звуками')),
                ('dict_games', models.TextField(blank=True, verbose_name='Словник з даними ігор ')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': '🎃 Користувач додаток',
                'verbose_name_plural': '🎃 Користувачі додаток',
            },
        ),
    ]
