# Generated by Django 5.0.4 on 2024-05-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natos', '0009_alter_games_options_userprofile_screensaver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(default='animations/test.svg', upload_to='animations')),
                ('name', models.CharField(max_length=30, verbose_name='Назва')),
                ('height', models.CharField(max_length=4, verbose_name='Висота')),
                ('width', models.CharField(max_length=100, verbose_name='Ширина')),
                ('description', models.CharField(max_length=100, verbose_name='Опис')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Анімація',
                'verbose_name_plural': 'Анімації',
            },
        ),
    ]
